version: '3.9'

services:
  scraper:
    build: .
    container_name: scraper
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=scraping_db
      - DB_USER=user
      - DB_PASS=password
    shm_size: '2gb'
    command: ["python", "src/scraper.py"]

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scraping_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data: